import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import {
  Google,
  NightShelterRounded,
  Facebook,
  Apple,
} from "@mui/icons-material";
import { api } from "../utils/api";
import { Input } from "../components/Input";
import { Button } from "../components/Button";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Nightlite</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-muted text-inverted">
        <div className="container m-8 flex max-w-xl flex-col items-center justify-center gap-6 rounded-md bg-foreground px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-inverted sm:text-[5rem] ">
            <NightShelterRounded className="text-primary" fontSize="inherit" />
            Nightlite
          </h1>
          <div className="grid grid-flow-col grid-cols-2 ">
            <Button type="text" active={true}>
              Sign In
            </Button>
            <Button type="text" active={false}>
              Sign Up
            </Button>
          </div>
          <div className="flex flex-col text-foreground">
            <Input />
            <Input />
          </div>

          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
          <div className="flex flex-col items-center gap-2">
            <Link
              className="rounded-full border-2 border-inverted py-2 px-3"
              href="/todo"
            >
              Continue As Guest
            </Link>
          </div>
          <div>
            <div className="divider text-center">or</div>
            <div>
              <div>
                <Button type="disabled">
                  <Google /> Sign in with Google
                </Button>
              </div>
              <div>
                <Button type="disabled">
                  <Facebook /> Sign in with Facebook
                </Button>
              </div>
              <div>
                <Button type="disabled">
                  <Apple /> Sign in with Apple
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-inverted">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="btn-primary"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
